name: CI Build Step - Deploy Image to ECR

on: workflow_dispatch

env:
  AWS_REGION: us-east-1              
  S3_REPOSITORY: lambdaboilerplate-builds
  TF_VERSION: '1.9.3'
  TG_VERSION: '0.63.6'
  TG_DIR: 'deploy/terragrunt/bounded-context-initialization'

jobs:
  deploy:
    name: Build zip to S3
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout cloud-deployment
        uses: actions/checkout@v4
        with:
          ref: 'feature/aws-lambda-boilerplate-deployment'
          repository: dashg-enterprises/cloud-deployment
          token: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          path: deploy
          sparse-checkout: |
            live/_initializations/lambda-boilerplate
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure Bounded Context is initialized
        uses: gruntwork-io/terragrunt-action@v2
        env:
          INPUT_PRE_EXEC_1: |
            git config --global url."https://user:${{secrets.CLOUD_DEPLOYMENT_PAT}}@github.com".insteadOf "https://github.com"
          INPUT_PRE_EXEC_2: |
            git config --global --list
        with:
          TF_VERSION: ${{ env.TF_VERSION }}
          TG_VERSION: ${{ env.TG_VERSION }}
          tg_dir: ${{ env.TG_DIR }}
          tg_command: 'apply --terragrunt-source ../../../..//iac/initialization'